# Generated by Django 5.1.6 on 2025-02-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_app', '0002_alter_user_data_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='profile_picture',
            field=models.ImageField(upload_to='profile_pictures/'),
        ),
    ]
